### ISSUE TITLE
Convert URDF to Xacro

### ISSUE THREAD

**Issue by Gregory-Meyer** [umigv/goat#153]
We can use Xacro to increase the compactness and readability of the GOAT's URDF. This is not a mainline issue, since the URDF will be the same with or without Xacro integration.

When this issue is closed, we should have a `goat.xacro` file which uses Xacro's math capabilities to more accurately specify positions and orientations and Xacro's parameter capabilities to specify visual and collision geometries.

http://wiki.ros.org/urdf/Tutorials/Using%20Xacro%20to%20Clean%20Up%20a%20URDF%20File

**Comment by Gregory-Meyer** [comment]
Moving this out of a milestone since it's not important for the most part

**Comment by MishFTW** [comment]
Backlog post comp
