### ISSUE TITLE
Generate Encoder Covariance Matrix

### ISSUE THREAD

**Issue by Gregory-Meyer** [umigv/goat#214]
In order for our state estimation nodes to work properly, we need covariances on every input. Since the encoder node is written by us, we need to find its covariance matrix. First, we need to find out how to generate the covariance matrix, then we need to generate, and then we need to incorporate it.

**Comment by MishFTW** [comment]
Linear motion complete, angles incomplete;

**Comment by MishFTW** [comment]
Kaizen:
Joseph doesn't know how to use robot on his own (run ROS); could have reached out to Greg/Sam

We may be missing some communal information on GOAT operating procedure; missing documentation on robot startup procedures @Gregory-Meyer

**Comment by Gregory-Meyer** [comment]
Added SLAM startup procedure to [Atlas](http://atlas.umigv.com/atlas/docs).

**Comment by MishFTW** [comment]
Need to recalibrate

**Comment by Gregory-Meyer** [comment]
The requirements for this have changed since encoder_odometry has been modified to output TwistWithCovarianceStamped messages. Need to test that the velocity output matches expected values for various speeds.
