### ISSUE TITLE
2d Cost Map

### ISSUE THREAD

**Issue by atish3** [umigv/goat#337]
TASK: Using an image that has been appropriately transformed (de-noised, kerneled, threshold tested, and regressed), produce a 2D cost map using the image. The cost map is what the robot will use to navigate, and will serve as its internal representation of its landscape.

ACCEPTANCE: The task will be considered complete when, given an appropriately transformed image, a 2d cost map is produced that accurately represents the surroundings shown in the original image.

**Comment by cedricIGV** [comment]
Issues with shifting frame and differing offsets in each picture. Need to derive 2D-cost map class. Updated time estimate.
