### ISSUE TITLE
Test Naviagtion Stack in Simulation

### ISSUE THREAD

**Issue by oliversno** [umigv/goat#379]
* Finish URDF and Gazebo Models
    - Add position information to Gazebo
* Create files for navigation stack to describe robot characteristics (bounding box etc.)
*Describe the layers of the navigation stack
    - Global and Local costmaps
    - Global and Local planners
* Generate map (pre-generate, from gazebo world?)

When this issues is closed we should be able to issue commands to the robot in RViz and the robot will respond in simulation.

**Comment by Gregory-Meyer** [comment]
aborted in favor of physical testing
