### ISSUE TITLE
Add odometric data to Gazebo model

### ISSUE THREAD

**Issue by Gregory-Meyer** [umigv/goat#380]
When this issue is closed, we should be able to invoke `rostopic echo /odometry/filtered` and get a stream of `sensor_msgs/Odometry` messages at 50Hz or more of the robot's current position, orientation, and velocity in free space.

**Comment by oliversno** [comment]
@Gregory-Meyer Should sensor_msgs/Odometry be nav_msgs/Odometry ? I can't seem to find any documentation on Odometry http://wiki.ros.org/sensor_msgs . However, this seems to be exactly what we want http://docs.ros.org/api/nav_msgs/html/msg/Odometry.html .

**Comment by Gregory-Meyer** [comment]
Yep that's exactly the one :+1:
