### ISSUE TITLE
Drill pilot holes into the prototype width pieces

### ISSUE THREAD

**Issue by camkab** [umigv/goat#383]
We have 2 each of the following 2x4 wooden lengths: 18",24", 30".

Drill 3 through-holes into the side of both ends of the 2x4 at a diameter of the screw such that there will be no threads formed when screwed together.

Make sure there is a consistent fixed distance between all the holes.

**Comment by karolinarak** [comment]
Drilled holes using LSA Machine Shop on Thursday Jan 24, taken to DL1 Jan 26th
