### ISSUE TITLE
Physical Testing Operations

### ISSUE THREAD

**Issue by cpmarsh** [umigv/goat#395]
A lot of logistics need to be considered when testing our robot at M-Air

-Who will be there? Members need orientation from Damen Provost to use the space
-How will we get the robot up there? We have the funds to rent vehicles on a short term basis if needed
-What do we need to bring with us? 
-What will we test for? Where will this data go?

These, and other items that we may not have considered yet, need to be properly handled. If done well, testing helps us make decisions immensely. If done improperly, it's a frustrating experience that always falls short of delivering what was promised. 

P.S. Don't be like Chris and Sam, wear warm clothes whenever testing happens outside :-P

**Comment by Gregory-Meyer** [comment]
testing season is over, closing
