### ISSUE TITLE
Simulation and Testing

### ISSUE THREAD

**Issue by cpmarsh** [umigv/goat#396]
Ideally, the robot will be tested in both a simulated and real world environment. While a simulation brings a lot of ease, such as not having to worry about physical conditions and being able to easily repeat and replay things, the competition ultimately takes place in a real field that comes with plenty of imperfections. The simulation and testing Epic encompasses both of these. 

1) Simulation - a proper framework using Gazebo and/or ROS is needed to visualize collected data, execute algorithms on that data, and study the results.

2) Real world - We have permission to use the field at M-Air for testing our robot under certain conditions, such as schedules we have to respect and proper orientation of members. This testing is something that needs to be ramped up - the only way to expose all the flaws in our design is to put it to the test.

**Comment by Gregory-Meyer** [comment]
aborted in favor of physical testing
