### ISSUE TITLE
Atlas documentation for starting up Tele-Op

### ISSUE THREAD

**Issue by cedricIGV** [umigv/goat#419]
Complete documentation of terminal commands for running Tele-Op on the robot.

**Comment by Gregory-Meyer** [comment]
I wrote up some instructions and stuck them under Engineering Standards->Testing Procedures, but there's something wrong with the website and it won't show up.

**Comment by Gregory-Meyer** [comment]
[Seems to be working now](http://atlas.umigv.com/testing-procedures) @gtheller @cedricIGV
