### ISSUE TITLE
Base Plate Design

### ISSUE THREAD

**Issue by camkab** [umigv/goat#424]
For our new frame, design the base plate.

The base plate will not support weight, so it can be thin and light. Consider different thicknesses and their weights. 

Different materials may include: aluminum, HDPE, Acrylic, etc

Consider cutouts for the gearbox and the chain paths.

Consider where attachment holes are.

**Comment by MxMoss3** [comment]
Base Plate Mass for varying materials and thicknesses:
https://drive.google.com/open?id=1wHt4WG_K19ExGS7IyAGkVgzIgMtQW7IKiTS6nua5tRs
